#!/usr/bin/env bash

git_alias=""

while true; do
  clear
  read -r nb_lines nb_cols <<<"$(stty size)"
  nb_lines="$((nb_lines - 1))"
  nb_cols="$((nb_cols))"

  if [[ "$(gsettings2 get org.gnome.desktop.interface color-scheme)" == "'prefer-light'" ]]; then
    git_alias="lgl"
  else
    git_alias="lg"
  fi

  git "$git_alias" --color=always \
    | awk -v cols="$nb_cols" '{
        visible=0; out=""; i=1
        while (i <= length($0)) {
          character = substr($0, i, 1)
          if (character == "\033" && substr($0, i+1, 1) == "[") {
            j = i + 2
            while (j <= length($0) && substr($0, j, 1) != "m") j++
            out = out substr($0, i, j-i+1)
            i = j + 1
          } else {
            if (visible < cols) { out = out character; visible++ }
            i++
          }
        }
        print out
      }' \
    | head -n "$nb_lines"
  inotifywait -qre close_write .git > /dev/null
done
